#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
#
# The name of a database user with read access to the database.
DBUSER=xxxxxx
# The password associated with the above user. Leave commented if none.
DBPASS=xxxxx
# The database associated with this repository.
DBNAME=commitInfo
DBHOST=localhost
# The path relative to the repository root in which to store the sql dump.
DBPATH=suivi
read -p "Sauvegarde de la base dans ce commit (y/[n]) ?" yn < /dev/tty
yn=${yn:n}
case $yn in
	 [Yy]* )
		  echo "commit verifie le " 'date' >> $DBPATH/$DBNAME.txt
		     git add $DBPATH/$DBNAME.txt
		      exit 0;;
		       [Nn]* )
			        exit 0;;
		esac
		exit 0
